package pkg2xb3;

import java.io.FileNotFoundException;

import javax.swing.JTextField;

/**
*
* @author Administrator
*/
public class gui extends javax.swing.JFrame {

   /**
    * Creates new form gui
    */
   public gui() {
       initComponents();
   }

   //
   private String reg;
   private String gen;
   private long low;
   private long high;
   private String temp;
   private int ega;
   JTextField txtField;
   //
   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

       buttonGroup1 = new javax.swing.ButtonGroup();
       jMenuItem1 = new javax.swing.JMenuItem();
       jLabel1 = new javax.swing.JLabel();
       Search = new javax.swing.JButton();
       age = new javax.swing.JSlider();
       RegionSelect = new javax.swing.JComboBox<>();
       jLabel2 = new javax.swing.JLabel();
       fromDate = new javax.swing.JTextField();
       toDate = new javax.swing.JTextField();
       jLabel3 = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();
       MaleOnly = new javax.swing.JRadioButton();
       FemaleOnly = new javax.swing.JRadioButton();
       DefaultGender = new javax.swing.JRadioButton();
       MaxAge = new javax.swing.JCheckBox();
       disAge = new javax.swing.JLabel();

       jMenuItem1.setText("jMenuItem1");

       setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

       jLabel1.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
       jLabel1.setText("Advanced Twitter Search Engine");
       jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
       jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseEntered(java.awt.event.MouseEvent evt) {
               jLabel1MouseEntered(evt);
           }
       });

       Search.setFont(new java.awt.Font("宋体", 1, 36)); // NOI18N
       Search.setText("Search");
       Search.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               try {
				SearchActionPerformed(evt);
			} catch (FileNotFoundException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
           }
       });

       age.setValue(0);
       age.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
       age.addMouseListener(new java.awt.event.MouseAdapter() {
           public void mouseReleased(java.awt.event.MouseEvent evt) {
               ageMouseReleased(evt);
           }
       });

       RegionSelect.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       RegionSelect.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "World", "Canada", "USA", "UK" }));
       RegionSelect.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               RegionSelectActionPerformed(evt);
           }
       });

       jLabel2.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       jLabel2.setText("Region:");

       fromDate.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       fromDate.setText("2009/09/01");

       toDate.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       toDate.setText("2010/01/30");

       jLabel3.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       jLabel3.setText("To:");

       jLabel4.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       jLabel4.setText("From:");

       buttonGroup1.add(MaleOnly);
       MaleOnly.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       MaleOnly.setText("Male Only");

       buttonGroup1.add(FemaleOnly);
       FemaleOnly.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       FemaleOnly.setText("Female Only");

       buttonGroup1.add(DefaultGender);
       DefaultGender.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       DefaultGender.setSelected(true);
       DefaultGender.setText("Default");

       MaxAge.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       MaxAge.setText("Maximum age:");
       MaxAge.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               MaxAgeActionPerformed(evt);
           }
       });

       disAge.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
       disAge.setText("0");

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap(35, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(jLabel2)
                               .addGap(18, 18, 18)
                               .addComponent(RegionSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(layout.createSequentialGroup()
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(layout.createSequentialGroup()
                                       .addComponent(jLabel4)
                                       .addGap(18, 18, 18))
                                   .addGroup(layout.createSequentialGroup()
                                       .addComponent(jLabel3)
                                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                   .addComponent(fromDate)
                                   .addComponent(toDate))))
                       .addGap(122, 122, 122)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(MaleOnly)
                           .addComponent(DefaultGender)
                           .addComponent(FemaleOnly)
                           .addGroup(layout.createSequentialGroup()
                               .addComponent(MaxAge)
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                               .addComponent(disAge, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                   .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
           .addComponent(Search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(layout.createSequentialGroup()
                       .addGap(70, 70, 70)
                       .addComponent(MaleOnly)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(FemaleOnly)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(DefaultGender)
                       .addGap(18, 18, 18)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(MaxAge)
                           .addComponent(disAge)))
                   .addGroup(layout.createSequentialGroup()
                       .addContainerGap()
                       .addComponent(jLabel1)
                       .addGap(18, 18, 18)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel2)
                           .addComponent(RegionSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGap(32, 32, 32)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                               .addComponent(jLabel4)))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel3))))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addContainerGap())
       );

       pack();
   }// </editor-fold>//GEN-END:initComponents

   private void SearchActionPerformed(java.awt.event.ActionEvent evt) throws FileNotFoundException {//GEN-FIRST:event_SearchActionPerformed
       System.out.println("Search!");// TODO add your handling code here:
       //
       //
       temp = fromDate.getText() + "000000";
       temp = temp.substring(0, 4) + temp.substring(5, 7) + temp.substring(8);
       low = Long.parseLong(temp);
       temp = toDate.getText() + "235959";
       temp = temp.substring(0, 4) + temp.substring(5, 7) + temp.substring(8);
       high = Long.parseLong(temp);
       reg = (String) RegionSelect.getSelectedItem();
       if (MaleOnly.isSelected())
    	   gen = MaleOnly.getLabel().substring(0, 4);
       else if (FemaleOnly.isSelected())
    	   gen = FemaleOnly.getLabel().substring(0, 6);
       else
    	   gen = DefaultGender.getLabel().substring(0, 7);
       ega = age.getValue();
       
       //
       //loadList jojo = new loadList();
       loadList.LoadUsers();
       search se = new search();
       System.out.println(ega + "  " + reg + "  " + low + "  " + high + "  " + gen);
       twitterADT[] tw = se.searchTweets(loadList.userList, ega, gen, reg, low, high);
       for (int i = 0; i <tw.length; i++) {
    	   System.out.println(tw[i].getTweets());
       }
       //
   }//GEN-LAST:event_SearchActionPerformed

   private void RegionSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegionSelectActionPerformed
       // TODO add your handling code here:
   }//GEN-LAST:event_RegionSelectActionPerformed

   private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
       // TODO add your handling code here:
   }//GEN-LAST:event_jLabel1MouseEntered

   private void ageMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ageMouseReleased
       disAge.setText(Integer.toString(age.getValue()));    // TODO add your handling code here:
       if(!MaxAge.isSelected()){
           MaxAge.doClick();}
   }//GEN-LAST:event_ageMouseReleased

   private void MaxAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxAgeActionPerformed
       // TODO add your handling code here:
	   //txtField = (JTextField) evt.getSource();
	   //ega = Integer.parseInt(txtField.getText());
   }//GEN-LAST:event_MaxAgeActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new gui().setVisible(true);
           }
       });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JRadioButton DefaultGender;
   private javax.swing.JRadioButton FemaleOnly;
   private javax.swing.JRadioButton MaleOnly;
   private javax.swing.JCheckBox MaxAge;
   private javax.swing.JComboBox<String> RegionSelect;
   private javax.swing.JButton Search;
   private javax.swing.JSlider age;
   private javax.swing.ButtonGroup buttonGroup1;
   private javax.swing.JLabel disAge;
   private javax.swing.JTextField fromDate;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JMenuItem jMenuItem1;
   private javax.swing.JTextField toDate;
   // End of variables declaration//GEN-END:variables
}
